version: '3.3'
services:
    alpine:
        image: icrar/eagle:${VCS_TAG}
        container_name: eagle_dev
        restart: "no"
        build:
            context: ..
            dockerfile: docker/Dockerfile.dev
        ports:
            - 8888:80/tcp
        volumes:
            - .:/app
