# Development version for EAGLE docker build. This enables a developer
# to work on the host directory and see the changes reflected in the
# conrainer.

FROM icrar/eagle-base:latest
COPY . .
RUN cd /app ; ln -sf docker/prestart.dev.sh prestart.sh
