import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const schemaPath = path.join(repoRoot, "static", "lg.graph.v4.schema");
const outputPath = path.join(repoRoot, "src", "generated", "lgGraphV4Schema.ts");
const checkOnly = process.argv.includes("--check");

const schema = JSON.parse(fs.readFileSync(schemaPath, "utf8"));
const generatedSource = `/*
#
#    ICRAR - International Centre for Radio Astronomy Research
#    (c) UWA - The University of Western Australia, 2016
#    Copyright by UWA (in the framework of the ICRAR)
#    All rights reserved
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
#    MA 02111-1307  USA
#
*/

import type { ExtendedJSONSchema } from "json-schema-to-ts";

// Snapshot of the canonical V4 schema from static/lg.graph.v4.schema.
// Generated by tools/generateLgGraphV4Schema.mjs.
export const lgGraphV4Schema = ${JSON.stringify(schema, null, 4)} as const satisfies ExtendedJSONSchema;
`;

if (checkOnly) {
    const currentSource = fs.readFileSync(outputPath, "utf8");

    if (currentSource !== generatedSource) {
        console.error(`Schema snapshot is out of date: ${path.relative(repoRoot, outputPath)}`);
        process.exit(1);
    }

    console.log(`Schema snapshot is up to date: ${path.relative(repoRoot, outputPath)}`);
    process.exit(0);
}

fs.writeFileSync(outputPath, generatedSource);
console.log(`Wrote ${path.relative(repoRoot, outputPath)} from ${path.relative(repoRoot, schemaPath)}`);
