name: Playwright Tests
on: [push]

jobs:
  test:
    name: Run Simple Test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: PIP install
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Compile Typescript
        run: tsc
      - name: Start server
        run: python eagleServer/eagleServer.py -t /tmp &

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
