name: TestCafe
on: [push]

jobs:
  test:
    name: Run Simple Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: NPM install
        run: npm install
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: PIP install
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Compile Typescript
        run: tsc
      - name: Start server
        run: python eagleServer/eagleServer.py -t /tmp &
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        env:
            EAGLE_GITHUB_ACCESS_TOKEN: ${{secrets.EAGLE_GITHUB_ACCESS_TOKEN}}
        with:
            args: "chrome tests/simple.js tests/drag-and-drop.js tests/edit-node-parameter.js tests/long_test.js"
